elo-placeholder: "%alonsoleagues_points%"
league-placeholder: "%alonsoleagues_league_display%"

auto-give-paper: true
paper-slot: 8

paper:
  name: "&6&l⭐ &b&lELO SIRALAMA &6&l⭐"
  lore:
    - ""
    - "&7Sag tiklayarak elo siralamasini"
    - "&7goruntuleyebilirsin!"
    - ""
    - "&eTop 250 oyuncu listelenir"
    - "&eKitap formatinda goruntulersin"
    - ""
    - "&a▶ Sag Tikla"

cache-update-interval: 60
max-players: 250

messages:
  prefix: "&8[&6EloTop&8] "
  no-permission: "&cYetkin yok!"
  no-data: "&cHenuz elo verisi bulunamadi!"

# ItemsAdder Rank Emojileri
# Elo araligina gore hangi ItemsAdder item kullanilacak
rank-icons:
  enabled: true
  ranks:
    # Bronz
    bronze-5:
      min-elo: 0
      max-elo: 349
      itemsadder-id: "rank_badge:rank_lv6"
    bronze-4:
      min-elo: 350
      max-elo: 499
      itemsadder-id: "rank_badge:rank_lv5"
    bronze-3:
      min-elo: 500
      max-elo: 749
      itemsadder-id: "rank_badge:rank_lv3"
    bronze-2:
      min-elo: 750
      max-elo: 999
      itemsadder-id: "rank_badge:rank_lv2"
    bronze-1:
      min-elo: 1000
      max-elo: 1000
      itemsadder-id: "rank_badge:rank_lv1"
    # Gumus
    silver-5:
      min-elo: 1001
      max-elo: 1359
      itemsadder-id: "rank_badge:rank_lv16"
    silver-4:
      min-elo: 1360
      max-elo: 1719
      itemsadder-id: "rank_badge:rank_lv15"
    silver-3:
      min-elo: 1720
      max-elo: 2079
      itemsadder-id: "rank_badge:rank_lv13"
    silver-2:
      min-elo: 2080
      max-elo: 2439
      itemsadder-id: "rank_badge:rank_lv12"
    silver-1:
      min-elo: 2440
      max-elo: 2799
      itemsadder-id: "rank_badge:rank_lv11"
    # Altin
    gold-5:
      min-elo: 2800
      max-elo: 3159
      itemsadder-id: "rank_badge:rank_lv26"
    gold-4:
      min-elo: 3160
      max-elo: 999999
      itemsadder-id: "rank_badge:rank_lv25"
