elo-placeholder: "%alonsoleagues_points%"
league-placeholder: "%alonsoleagues_league_display%"

auto-give-paper: false
paper-slot: 8

paper:
  name: "&6&l⭐ &b&lELO SIRALAMA &6&l⭐"
  lore:
    - ""
    - "&7Sag tiklayarak elo siralamasini"
    - "&7goruntuleyebilirsin!"
    - ""
    - "&eTop 250 oyuncu listelenir"
    - ""
    - "&a▶ Sag Tikla"

cache-update-interval: 60
max-players: 250

messages:
  prefix: "&8[&6EloTop&8] "
  no-permission: "&cYetkin yok!"
  no-data: "&cHenuz elo verisi bulunamadi!"

rank-icons:
  enabled: true

  # YONTEM 1: Lig bazli (oncelikli)
  leagues:
    BRONZ5:
      placeholder: "%img_rank1%"
    BRONZ4:
      placeholder: "%img_rank2%"
    BRONZ3:
      placeholder: "%img_rank3%"
    BRONZ2:
      placeholder: "%img_rank4%"
    BRONZ1:
      placeholder: "%img_rank5%"
    GUMUS5:
      placeholder: "%img_rank11%"
    GUMUS4:
      placeholder: "%img_rank12%"
    GUMUS3:
      placeholder: "%img_rank13%"
    GUMUS2:
      placeholder: "%img_rank14%"
    GUMUS1:
      placeholder: "%img_rank15%"

  # YONTEM 2: Elo bazli (fallback)
  ranks:
    rank1:
      min-elo: 0
      max-elo: 349
      placeholder: "%img_rank1%"
    rank2:
      min-elo: 350
      max-elo: 499
      placeholder: "%img_rank2%"
    rank3:
      min-elo: 500
      max-elo: 749
      placeholder: "%img_rank3%"
    rank4:
      min-elo: 750
      max-elo: 999
      placeholder: "%img_rank4%"
    rank5:
      min-elo: 1000
      max-elo: 1000
      placeholder: "%img_rank5%"
    rank11:
      min-elo: 1001
      max-elo: 1359
      placeholder: "%img_rank11%"
    rank12:
      min-elo: 1360
      max-elo: 1719
      placeholder: "%img_rank12%"
    rank13:
      min-elo: 1720
      max-elo: 2079
      placeholder: "%img_rank13%"
    rank14:
      min-elo: 2080
      max-elo: 2439
      placeholder: "%img_rank14%"
    rank15:
      min-elo: 2440
      max-elo: 999999
      placeholder: "%img_rank15%"
# Web Leaderboard - Gist ayarlari
web:
  gist-id: "38dbdb145473beabfcd22dea17600f45"
  github-token: "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"
  upload-interval: 5
